name: Docker Build Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ghcr.io/bayu-aditya/bayu-aditya-backend

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Github Container Registry
        env:
          token: ${{ secrets.TOKEN_GHCR }}
        run: echo $token | docker login ghcr.io --username bayu-aditya --password-stdin

      - name: Build Docker Image
        run: DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE_NAME:${GITHUB_SHA:0:4} .

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE_NAME:${GITHUB_SHA:0:4}

      - name: Kubernetes Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image -n bayu-staging deployment/bayu-aditya-backend core=$DOCKER_IMAGE_NAME:${GITHUB_SHA:0:4}